theme: minima 
title: Spherical-Harmonics-based Sound Field Decomposition and Multichannel NMF for Sound Source Separation. 
description: Joint work between Politecnico di Milano and University of Jaen
header_pages:
  -about.md
